name: inquiry

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  SKLandCheckIn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Prepare module
      run: |
        pip3 install -r requirements.txt
    - name: Run inquiry
      env:
        DINGTALKTOKEN: ${{ secrets.DINGTALKTOKEN }}
      run: |
        python Inquiry.py